# Generated by Django 3.2.11 on 2022-05-17 16:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=25)),
                ('dateof', models.DateTimeField(default=django.utils.timezone.now)),
                ('auth', models.IntegerField()),
                ('ip', models.CharField(default='', max_length=25)),
                ('session_key', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=25)),
                ('password', models.CharField(max_length=50)),
                ('createdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField()),
                ('salt', models.CharField(default='', max_length=25)),
                ('profile_type', models.IntegerField(null=0)),
                ('email', models.EmailField(max_length=50)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=50)),
                ('last_login', models.DateTimeField(null=True)),
                ('online', models.BooleanField(default=False)),
                ('expire_pwd', models.DateTimeField(default=datetime.datetime(2022, 8, 15, 16, 37, 16, 416951, tzinfo=utc))),
                ('ip', models.CharField(default='', max_length=25)),
                ('session_key', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('dateof', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip', models.CharField(default='', max_length=25)),
                ('session_key', models.CharField(default='', max_length=100)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_user', to='accounts.users')),
            ],
        ),
    ]
