# Generated by Django 3.2.11 on 2022-05-17 21:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_log',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='expire_pwd',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 15, 21, 12, 54, 904489, tzinfo=utc)),
        ),
    ]
