# Generated by Django 3.2.11 on 2022-05-18 20:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220517_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='online',
        ),
        migrations.AlterField(
            model_name='users',
            name='expire_pwd',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 16, 20, 58, 45, 577320, tzinfo=utc)),
        ),
    ]
